services:
  sentinel-app:
    build:
      context: ./
    restart: unless-stopped
    expose:
      - "8000"
    environment:
      PROJECT_NAME: ${PROJECT_NAME}
      DATABASE_NAME: ${DATABASE_NAME}
      DATABASE_URL: ${DATABASE_URL}
      API_BASE_URL: ${API_BASE_URL}
      JWT_SECRET_KEY: ${JWT_SECRET_KEY}
      PASSWORDS_SALT_SECRET_KEY: ${PASSWORDS_SALT_SECRET_KEY}
      SMTP_HOST: ${SMTP_HOST}
      SMTP_PORT: ${SMTP_PORT}
      SMTP_USER: ${SMTP_USER}
      SMTP_PASSWORD: ${SMTP_PASSWORD}
      SMTP_SENDER: ${SMTP_SENDER}
      SMTP_USE_TLS: ${SMTP_USE_TLS}
      BACKEND_CORS_ORIGINS: ${BACKEND_CORS_ORIGINS}
